apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: choki-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: choki-deploy
  template:
    metadata:
      labels:
        app: choki-deploy
    spec:
      containers:
      - image: choki09/agrocd:latest
        name: pet
